# ref. http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html

AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String
    Default: ''
  CfComment:
    Type: String
    Default: ''
  LambdaFunctionARN:
    Type: String
    Default: ''
  UserAgentForAccessRestriction:
    Type: String
    Default: ''

Conditions:
  ExistLambdaFunctionARN: !Not [!Equals [ !Ref LambdaFunctionARN, '' ]]
  ExistUserAgent: !Not [!Equals [ !Ref UserAgentForAccessRestriction, '' ]]

Resources:
  ######
  # S3
  ######
  # http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/quickref-s3.html
  # http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
  myS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}
      WebsiteConfiguration:
        IndexDocument: index.html
    DeletionPolicy: Retain
  myBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref myS3Bucket
                - /*
            Condition:
              !If
                - ExistUserAgent
                - StringEquals:
                    aws:UserAgent: !Sub ${UserAgentForAccessRestriction}
                - !Ref AWS::NoValue
      Bucket: !Ref myS3Bucket
    DeletionPolicy: Retain

  ######
  # CloudFront
  ######
  # http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/quickref-cloudfront.html
  # http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution.html
  myDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Join
            - ''
            -
              - !Ref myS3Bucket
              - !Sub .s3-website-${AWS::Region}.amazonaws.com
          Id: !Join
            - ''
            -
              - S3-Website-
              - !Ref myS3Bucket
              - !Sub .s3-website-${AWS::Region}.amazonaws.com
          # S3OriginConfig:
          #   OriginAccessIdentity: ''
          CustomOriginConfig:
            OriginProtocolPolicy: http-only
          OriginCustomHeaders:
            - !If
                - ExistUserAgent
                - HeaderName: User-Agent
                  HeaderValue: !Sub ${UserAgentForAccessRestriction}
                - !Ref AWS::NoValue
        DefaultCacheBehavior:
          TargetOriginId: !Join
            - ''
            -
              - S3-Website-
              - !Ref myS3Bucket
              - !Sub .s3-website-${AWS::Region}.amazonaws.com
          # ViewerProtocolPolicy: allow-all
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
          - GET
          - HEAD
          MinTTL: 0
          MaxTTL: 0
          DefaultTTL: 0
          ForwardedValues:
            Cookies:
              Forward: all
            QueryString: true
          Compress: true
          LambdaFunctionAssociations:
            !If
              - ExistLambdaFunctionARN
              -
                - EventType: viewer-request
                  LambdaFunctionARN: !Sub ${LambdaFunctionARN}
              - !Ref AWS::NoValue
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        HttpVersion: http2
        DefaultRootObject: index.html
        Comment: !Sub ${CfComment}
        Enabled: true
    DeletionPolicy: Retain
