# ref. http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html

AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String
    Default: static-website-sample-stg
  Stage:
    Type: String
    Default: Staging

Resources:
  ######
  # S3
  ######
  # http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/quickref-s3.html
  # http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
  myS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}
      WebsiteConfiguration:
        IndexDocument: index.html
    DeletionPolicy: Retain
  myBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref myS3Bucket
                - /*
      Bucket: !Ref myS3Bucket

  ######
  # CloudFront
  ######
  # http://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/quickref-cloudfront.html
  myDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Sub ${ProjectName}.s3-website-${AWS::Region}.amazonaws.com
          Id: !Sub S3-Website-${ProjectName}.s3-website-${AWS::Region}.amazonaws.com
          # S3OriginConfig:
          #   OriginAccessIdentity: ''
          CustomOriginConfig:
            OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: !Sub S3-Website-${ProjectName}.s3-website-${AWS::Region}.amazonaws.com
          ViewerProtocolPolicy: allow-all
          AllowedMethods:
          - GET
          - HEAD
          MinTTL: 0
          MaxTTL: 0
          DefaultTTL: 0
          ForwardedValues:
            Cookies:
              Forward: all
            QueryString: true
          Compress: true
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        HttpVersion: http2
        DefaultRootObject: index.html
        Comment: !Sub ${Stage}
        Enabled: true
